CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
TOOL_ROOTS := tracer#tracer #champsim_tracer

include $(CONFIG_ROOT)/makefile.config
include $(CONFIG_ROOT)/makefile.default.rules


PINPLAY_HOME=$(PIN_KIT)/extras/pinplay/
PINPLAY_INCLUDE_HOME=$(PINPLAY_HOME)include
PINPLAY_LIB_HOME=$(PINPLAY_HOME)lib/$(TARGET_LONG)
EXT_LIB_HOME=$(PINPLAY_HOME)lib-ext/$(TARGET_LONG)
CXXFLAGS := -I$(PINPLAY_INCLUDE_HOME)

  
