#ifndef USER_H
#include <iostream>
using namespace std;

int KNOB_TRANSLATION_QUEUE = 0;
int KNOB_TTP = 0;
int KNOB_STLB_DO_NOT_TRACK_MISS = 0;



// STT_MRAM
int KNOB_STTMRAM_STLB = 0;

// SOTA
int KNOB_VICTIMA = 0;
int KNOB_EXTEND_VICTIMA = 0; // It needs Victima Enabled
int KNOB_HASH_CACHE_MAX_LIMIT = 64;
int KNOB_IDEAL_VICTIMA = 0;

int KNOB_POMTLB = 0;

int KNOB_SMT_ENABLE = 0;

int KNOB_PSCL_ROOT_LEVEL = 0;
int KNOB_LIVE_INPUT = 0;

int KNOB_ENABLE_LOG = 0;

int KNOB_ENABLE_MFOE_V2 = 0;

int KNOB_ENABLE_CTX = 0;

int KNOB_ENABLE_SWAT_WAYS = 0;
int KNOB_ENABLE_IDEAL_SWAT = 0;
int KNOB_ENABLE_SWAT_WAYS_OVERWRITE = 0;

#endif